// Generated by CoffeeScript 1.10.0
(function() {
  var all_names, app, capitalize, exphbs, express;

  express = require('express');

  exphbs = require('express-handlebars');

  app = express();

  all_names = ['world'];

  app.engine('handlebars', exphbs({
    defaultLayout: 'main'
  }));

  app.set('view engine', "handlebars");

  app.get('/', function(request, response) {
    return response.render('home');
  });

  app.get('/getname', function(request, response) {
    var name;
    name = request.query.name;
    all_names.push(name.toString());
    return response.render('names', {
      name: capitalize(name),
      all_names: all_names
    });
  });

  app.get('/allnames', function(request, response) {
    var title;
    title = "All Names Ever";
    return response.render("names", {
      'names': all_names,
      'title': title
    });
  });

  app.listen(8888);

  capitalize = function(word) {
    return word = word[0].toUpperCase() + word.slice(1).toLowerCase();
  };

  console.log('Server running on localhost:8888');

}).call(this);
