// Generated by CoffeeScript 1.10.0
(function() {
  var all_names, app, capitalize, exphbs, express;

  express = require('express');

  exphbs = require('express-handlebars');

  app = express();

  all_names = {
    'world': 1
  };

  app.engine('handlebars', exphbs({
    defaultLayout: 'main'
  }));

  app.set('view engine', "handlebars");

  app.get('/', function(request, response) {
    return response.render('home');
  });

  app.get('/getname', function(request, response) {
    var name;
    name = capitalize(request.query.name);
    if (all_names[name] == null) {
      all_names[name] = 1;
    } else {
      all_names[name] += 1;
    }
    return response.render('names', {
      name: name,
      all_names: all_names
    });
  });

  app.get('/allnames', function(request, response) {
    var name, title;
    name = name;
    title = "All Names Ever";
    return response.render("names", {
      all_names: all_names,
      name: name
    });
  });

  app.listen(8888);

  capitalize = function(word) {
    return word = word[0].toUpperCase() + word.slice(1).toLowerCase();
  };

  console.log('Server running on localhost:8888');

}).call(this);
